services:
  dyma-postgresql:
    image: postgres:15
    container_name: dyma-postgres-production
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5ML^Es#x%4U&DK6c
    ports:
      - "5424:5432"
    volumes:
      - dyma-postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  dyma-postgres-data: